# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1

# - powershell: |
#     $ProgressPreference = 'SilentlyContinue'
#     Write-Host "::::::::::::::::::::::Downloading .Net Framework v4.5:::::::::::::::::::::::"
#     Invoke-WebRequest -Uri "https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net452-developer-pack-offline-installer" -OutFile "$env:TEMP\dotnet-sdk-4.5.2-win-x64.exe"
#     Start-Process "$env:TEMP\dotnet-sdk-4.5.2-win-x64.exe" -ArgumentList '/quiet', '/norestart' -Wait
#    Remove-Item "$env:TEMP\dotnet-sdk-4.5.2-win-x64.exe"
# - task: NuGetCommand@2
#   inputs:
#     command: 'custom'
#     arguments: 'install Microsoft.NETFramework.ReferenceAssemblies.net45 -version 4.5.2'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install Microsoft.NETFramework.ReferenceAssemblies.net45 -version 4.5.2'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:TargetFramework=v4.5 /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
# - task: VSBuild@1
#   inputs:
#     solution: 'SampleApp.sln'
#     msbuildArgs: '/p:TargetFramework=v4.5'
#     platform: 'x64'
#     configuration: 'Release'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
